# Generated by Django 2.2.3 on 2019-07-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myappparisportif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parisportif',
            name='rencontre_pays',
            field=models.CharField(max_length=255),
        ),
    ]
